#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  identificadorCategorial.py
#  
#  Copyright 2017 mapa <mapa@jules>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  


# lista de morfemas de género
# lista de morfemas de número
# bases léxicas susceptibles de morfemas de género y número

morf_genero_fem = "a"
morf_genero_mas = "o"
morf_numero_sing = " "
morf_numero_plur = "s"
  
sust_m_marca_genero_e = ["rinoceronte", "bisonte"]

sust_m_sin_marca_genero_c = ["licor", "iluminación", "tazón", "camión", "azúcar", "huracán", "clavel",
                             "baúl", "caudal"]

sust_m_con_marca_o_genero = ["teléfono", "cuadro", "acueducto", "libro", "misterio", "plato", "tarjetero",
                           "barco", "triángulo", "ojo",  "piano",  "cuaderno"]

sust_0_base = ["gat", "bols", "amig", "compañer", "pes"]

sust_f_con_marca_a_genero = ["cadena", "pantera", "luna", "guitarra", "flauta","agua", "agenda","quimera",
                             "copa", "agua", "tarjeta", "mesa", "sacerdotiza", "corchetera", "ventana",
                             "taza",  "letra","duna", "silla", , "pastilla", "vaca", "piedra", "boa", "estrella",
                            "culebra", "orbita"]

sust_f_sin_marca_genero = ["flor", "luz", "cal", "señal", "sal", "miel", "lombriz", "perdiz", "cruz"]

sust_f_marca_genero_e = ["elipse", "techumbre"]




########################################    
lista_adjetivos_m = ["musical", "caluroso", "misterioso", "lejano", "blanquecino", "amargo","cronológico", "transparente",
                    "delgado", "rojizo", "húmedo", "duradero", "divino", "pesado", "suculento", "tierno",
                    "mostruoso", "alaraco", "tormentoso", "calamitoso", "amarillento", "emplumado", "viscoso"]
lista_adjetivos_f = ["musical", "rugosa", "misteriosa", "sabrosa", "victoriosa", "acaudalada","tierna",
                     "delicada", "rosada", "cristalina", "dura", "hermética", "funcional", "terrible",
                    "tímida", "acuosa", "enfermiza", "azulada", "parduzca", "ovalada", "metódica"]
lista_verbos_inf = ["arder", "arrugar", "enmascarar", "cosechar", "comer", "alejar","morder", "sufrir", 
                    "viajar", "escribir", "leer", "diagramar", "elegir", "adormecer", "pelear", "besar",
                   "arriesgar", "tramar", "perder", "soñar", "levitar", "acorralar", "visitar", "acampar"]
lista_adverbios = ["rápidamente", "lentamente", "mucho", "ahí", "acá", "lejos", "cerca", "nunca", "así",
                   "demasiado", "temprano", "ahora", "deprisa", "peor", "ayer", "sorpresivamente",
                   "bastante","apenas","aquí", "allí", "allá"]





