#!/usr/bin/env python
# -*- coding: utf-8 -*-
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  identificadorCategorial.py


import pdb
from subprocess import call
import random

# lista de morfemas de género
# lista de morfemas de número
# bases léxicas susceptibles de morfemas de género y número

morf_genero_fem = "a"
morf_genero_mas = "o"
morf_numero_sing = " "
morf_numero_plur = "s"
  
sust_m_marca_genero_e = ["rinoceronte", "bisonte", "estudiante"]

sust_m_sin_marca_genero_c = ["licor", "iluminación", "tazón", "camión", "azúcar", "huracán", "clavel",
                             "baúl", "caudal"]

sust_m_con_marca_o_genero = ["teléfono", "cuadro", "acueducto", "libro", "misterio", "plato", "tarjetero",
                           "barco", "triángulo", "ojo",  "piano",  "cuaderno"]

sust_0_base = ["gat", "bols", "amig", "compañer", "pes", "loc", "mosc"]

sust_f_con_marca_a_genero = ["cadena", "pantera", "luna", "guitarra", "flauta","agua", "agenda","quimera",
                             "copa", "agua", "tarjeta", "mesa", "sacerdotiza", "corchetera", "ventana",
                             "taza",  "letra","duna", "silla", "pastilla", "vaca", "piedra", "boa", "estrella",
                            "culebra", "orbita"]

sust_f_sin_marca_genero = ["flor", "luz", "cal", "señal", "sal", "miel", "lombriz", "perdiz", "cruz", "hiel"]

sust_f_marca_genero_e = ["elipse", "techumbre", "costumbre"]


# longitudes de cada lista
n_sust_m_marca_genero_e = len(sust_m_marca_genero_e)
n_sust_m_sin_marca_genero_c = len(sust_m_sin_marca_genero_c)
n_sust_m_con_marca_o_genero = len(sust_m_con_marca_o_genero)
n_sust_0_base =len(sust_0_base)
n_sust_f_con_marca_a_genero = len(sust_f_con_marca_a_genero)
n_sust_f_sin_marca_genero = len(sust_f_sin_marca_genero)
n_sust_f_marca_genero_e = len(sust_f_marca_genero_e)

print(n_sust_m_marca_genero_e)
print(n_sust_m_sin_marca_genero_c)
print(n_sust_m_con_marca_o_genero)
print(n_sust_0_base)
print(n_sust_f_con_marca_a_genero)
print(n_sust_f_sin_marca_genero)
print(n_sust_f_marca_genero_e)


select_categ = random.randint(1, 7)

if select_categ == 1:
        cat_preg = sust_m_marca_genero_e
if select_categ == 2:
        cat_preg = sust_m_sin_marca_genero_c
if select_categ == 3:
        cat_preg = sust_m_con_marca_o_genero
if select_categ == 4:
        cat_preg = sust_0_base
if select_categ == 5:
        cat_preg = sust_f_con_marca_a_genero
if select_categ == 6:
        cat_preg = sust_f_con_marca_a_genero
if select_categ == 7:
        cat_preg = sust_f_marca_genero_e

print(select_categ)

posible = random.choice(cat_preg)

print(posible)
