#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  eneDeSilabas.py
#  
#  Copyright 2018 Pedro Domingo Roman <historiadores@iMac-de-Pedro.local>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

import pdb
from subprocess import call
import random
import time

# Limpiar la pantalla 

reporte01 = "Has respondido "
reporte02 = " respuestas correctas de un total de "
reporte03 = "Has tenido "

reporte05 = "Demoras "
reporte06 = " segundos aproximadamente en cada respuesta."
reporte07 = "Tu porcentaje de logro es de "
reporte08 = " por ciento."
entrada = "Presiona ENTER"

call("clear")

# Enunciado respuesta correcta
enunciados_correctas = ["Veo que respondes bastante bien", "Felicitaciones. No pensé que responderías bien", "Excelente, excelente... muy bien", 
                       "Efectivamente. Tu respuesta es correcta", "Lo hiciste bien. Muy bien"]

# Enunciado respuesta incorrecta
enunciados_incorrectas = ["Te equivocaste", "No, no, no, no...", "Error", "Mmmm... la verdad es que no.", 
                          "Creo que estás en un error...", "Simplemente no y no (no es no)"]

# Listas de palabras
# Listas de palabras
una = ["ay", "baúl", "bien", "buen", "buey", "búho", "cae", "cien", "coa", "cuan", "diez", "dio", "dios", 
       "doy", "fue", "hay", "hiel", "hoy",  "juez", "laúd", "ley", "loa", "miau" ,"miel", "mohai", "neón", 
       "nuez", "pía", "pie", "piel", "púa", "pues", "quien", "riel", "roe", "ruin", "seis", "soez",
       "soy", "veo", "vía", "vial", "vio"] 

dos = ["agua",  "aún", "boa", "caos", "cahuín", "caer", "caigo", "ciudad", "coa","crear", "creer", 
        "cuatro", "diario", "fía", "guión", "leer","leo", "lío", "loa", "Mario",  "mía",  "moho", "muere", "nueva", 
        "nueve", "peor", "perdió", "piedra", "pía", "pierde","vea", "viuda"]
        
tres = [ "acuario", "acuosa",  "ahora", "área", "aseo", "beato", "caoba",  "causeo", "cuidado",  "faena", 
         "Lisboa", "María","fealdad", "poema", "presea", "toalla", "recrear", "marear", "paella", "posee", 
         "maestro", "óleo", "pétreo", "saeta"]
cuatro = ["viajaría", "demasiado", "cuidaría", "misionero", "acueducto", "perdiciones", "mueblería",
           "aéreo", "venérea", "biología", "aparean", "caedizo", "saborear", "maestría"]
cinco = ["aovillado", "aleatorio", "afianzaría", "puerilidades", "ecuanimidad", "eternidades", "claudicaría",
         "acarréanlo", "aleatorio","coordinación"]


# longitudes de cada lista
l_una = len(una)
l_dos = len(dos)
l_tres = len(tres)
l_cuatro = len(cuatro)
l_cinco = len(cinco)

# aleatorización del número de preguntas
ene_veces = random.randint(7, 20)

print("Tendrás que responder",ene_veces,"preguntas")
print("Verás una palabra y tendrás que decir cuántas sílabas tiene")
print("...")
print(entrada)

espera = (input())

contador_correctas = 0
contador_incorrectas = 0

inicio = time.time()

for i in range(ene_veces):
    call("clear")
    print("Escribe el número de sílabas")
    categoria = random.randint(1, 5)
    if categoria == 1:
        cat_preg = una
    if categoria == 2:
        cat_preg = dos
    if categoria == 3: 
        cat_preg = tres
    if categoria == 4:
        cat_preg = cuatro
    if categoria == 5:
        cat_preg = cinco

    n_sel_item = random.randint(1, 5)
    qu = cat_preg[n_sel_item]

    print(qu) 
    resp = int(input())

    if cat_preg == una and resp == 1:
       contador_correctas = contador_correctas + 1
       print(random.choice(enunciados_correctas))
       espera = (input("Presiona enter"))
    elif cat_preg == una and resp != 1:
       contador_incorrectas = contador_incorrectas + 1 
       print(random.choice(enunciados_incorrectas))
       espera = (input("Presiona enter"))    
    if cat_preg == dos and resp == 2:
       contador_correctas = contador_correctas + 1
       print(random.choice(enunciados_correctas))
       espera = (input("Presiona enter"))
    elif cat_preg == dos and resp != 2:
       contador_incorrectas = contador_incorrectas + 1 
       print(random.choice(enunciados_incorrectas))
       espera = (input("Presiona enter"))      
    if cat_preg == tres and resp == 3:
       contador_correctas = contador_correctas + 1
       print(random.choice(enunciados_correctas))
       espera = (input("Presiona enter"))
    elif cat_preg == tres and resp != 3:
       contador_incorrectas = contador_incorrectas + 1 
       print(random.choice(enunciados_incorrectas))
       espera = (input("Presiona enter"))       
    if cat_preg == cuatro and resp == 4:
       contador_correctas = contador_correctas + 1
       print(random.choice(enunciados_correctas))
       espera = (input("Presiona enter"))
    elif cat_preg == cuatro and resp != 4:
       contador_incorrectas = contador_incorrectas + 1 
       print(random.choice(enunciados_incorrectas))
       espera = (input("Presiona enter"))
    if cat_preg == cinco and resp == 5:
       contador_correctas = contador_correctas + 1
       print(random.choice(enunciados_correctas))
       espera = (input("Presiona enter"))
    elif cat_preg == cinco and resp != 5:
       contador_incorrectas = contador_incorrectas + 1 
       print(random.choice(enunciados_incorrectas))
       espera = (input("Presiona enter"))

final = time.time()

# cuenta el tiempo del proceso total
tiempo_total = final-inicio
tiempo_por_pregunta = round(tiempo_total/ene_veces,3)

if contador_incorrectas == 0:
    reporte04 = " equivocación"
elif contador_incorrectas == 1:
    reporte04 = " equivocación."
elif contador_incorrectas > 1:
    reporte04 = "equivocaciones"
	

	
cuantas_correctas =str(contador_correctas)
cuantas_preguntas = str(ene_veces)
cuantas_incorrectas =str(contador_incorrectas)
cuanto_tiempo_por_pregunta = str(tiempo_por_pregunta)

if tiempo_por_pregunta <= 3:
	evaluacion_tiempo = "rápido"
elif tiempo_por_pregunta > 3 and tiempo_por_pregunta < 6:
	evaluacion_tiempo = "regular"
elif tiempo_por_pregunta >= 6:
	evaluacion_tiempo = "lento"


# porcentaje de acierto
porcentaje = contador_correctas *100/ ene_veces
# a dos decimales
porcentaje = round(porcentaje,2)
# convertir a string
porcentaje_str = str(porcentaje)

call("clear")

if porcentaje == 100:
	print("Estás muy muy bien. Felicitaciones. :)")
elif porcentaje < 100 and porcentaje >= 80:
	print("Estás bien; aunque puedes mejorar un poco todavía. ;)")
elif porcentaje < 80 and porcentaje >= 50:
	print("Tendrás que mejorar bastante :/")
elif porcentaje < 50:
	print("La verdad es que estás muy mal. Tendrás que hacer algo.  :(")

print("")
print(reporte01+ cuantas_correctas+reporte02+cuantas_preguntas+'.')
print("")
print(reporte03 + cuantas_incorrectas+ reporte04)
print("")
print(reporte05 + cuanto_tiempo_por_pregunta+reporte06)
print("")
print("Lo que se considera más bien...")
print(evaluacion_tiempo)
print(reporte07+ porcentaje_str + reporte08)

