#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  graf.py



# Gráficos en matplotlib


# cargar librerías

import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl

#1   ############

# Crea figura

#fig = plt.figure()  # an empty figure with no axes
#fig.suptitle('No axes on this figure')  # Add a title so we know which it is
#fig, ax_lst = plt.subplots(3, 3)  # a figure with a 2x2 grid of Axes


#plt.show("fig") # Este es el comando que muestra la figura

#################
#################



# 2   ############

# x = np.linspace(0, 2, 100)
# plt.plot(x, x, label='lineal')
# plt.plot(x, x**2, label='cuadrática')
# plt.plot(x, x**3, label='cúbica')
# plt.xlabel(' etiqueta X')
# plt.ylabel('etiqueta Y')
# plt.title("Simple Plot")
# plt.legend()
# plt.show()



# 3. ################

# x = np.arange(0, 20, 0.2) # El tercer valor da número de muestra
# y = np.sin(x)
# fig, ax = plt.subplots()
# ax.plot(x, y)
# plt.show()



# 4 #################

# plt.ioff()
# for i in range(5):
#    plt.plot(np.random.rand(10))
#    plt.show()







# 5 #################

plt.plot(["a", "b", "c", "d", "e"], [1, 3,4, 17.5, 16], 'ro:')

plt.axis([0,6,0,20])

plt.ylabel('some numbers')
plt.show()


### fin de silab:
print('Obtienes ponderados ' + puntos_para_tramo + 'puntos, lo que te clasifica en el tramo ' + tramo)
print("#################")

# print("Cantidad de palabras de cada lista: 1, 2, 3, 4 y 5 sílabas")
# print(l_una)
# print(l_dos)
# print(l_tres)
# print(l_cuatro)
# print(l_cinco)


variables = ["Tiempo de respuesta", "referencia máxima","Porcentaje de logro", "Puntaje ponderado"]
valores = [tiempo_por_pregunta, 100, porcentaje, puntos_tramo]

graf = plt.plot(variables,valores)

plt.setp(graf, color='r', linewidth=2.0)

plt.show()
